"""Run the HESO/1 conformance vectors against this clean-room reference verifier.

Two corpora are executed:

  1. The LEGACY web-observation goldens (``vectors/heso-1.0-vectors.json``):
       - every plat vector: assert ``plat_hash(input_json)`` == recorded hash.
       - the sealed-envelope vector: assert
         ``verify_sealed_plat(sealed_envelope_json)`` == expected outcome.
     (The old un-run ``receipt_vector`` was dropped in P1 — see the
     ``_dropped_receipt_vector`` note in that file. Its receipt coverage moved to
     the rust-reference ``action_receipt_v2`` corpus below.)

  2. The CROWN-JEWEL goldens (``vectors/heso-1.0-crown-vectors.json``):
       - ``action_receipt_v2``  : ``verify_action_receipt`` == expected outcome.
       - ``chain``              : ``verify_chain`` == expected outcome.
       - ``redaction``          : ``verify_reveal`` agrees with ``reveal_verifies``.
       - ``taxonomy_classify``  : clean-room ``classify`` == expected class/verb/
                                  primitive/effect (over the open ``taxonomy.toml``).
       - ``rfc6962``            : leaf/node/empty hashes + inclusion proof reproduce.
       - ``dsse_pae``           : ``dsse_pae`` reproduces ``pae_hex`` and
                                  ``verify_dsse`` accepts the golden envelope.

  3. The commitment WIRE-PAYLOAD goldens (``vectors/heso-1.0-wire-vectors.json``,
     P3 / ADR-0003):
       - ``commitment_wire``    : clean-room re-derivation of the FULL receipt ->
                                  commitment+indexes projection byte-matches the
                                  recorded ``wire_payload``; the source receipt
                                  verifies; and NO raw-content substring survives
                                  onto the wire.
       - ``redact_before_sign`` : the redacted source receipt verifies, the reveal
                                  recomputes (good salt yes / bad salt no), and
                                  neither the raw value nor the reveal salt is on
                                  the wire.
       - ``primitive_index``    : the five-spine destructive-primitive enum + each
                                  case's (primitive, decision) are in-spine.

Exit 0 iff every vector passes; exit 1 (printing a diff per failure) otherwise.

The legacy crypto constants in the vectors file are real (generated by the Rust
reference). If a value still holds the ``<GENERATED_AT_MERGE>`` placeholder it is
reported PENDING and the run exits non-zero — that path remains for safety but no
crown vector ships a placeholder.
"""

from __future__ import annotations

import json
import os
import sys

import heso_verify as hv

# The merge-time sentinel a vector field carries until the conformance job fills
# it from the Rust reference. Matched as a PREFIX so variants like
# "<GENERATED_AT_MERGE:foo>" are caught too.
PLACEHOLDER_PREFIX = "<GENERATED_AT_MERGE"

_VEC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "vectors")
LEGACY_PATH = os.path.join(_VEC_DIR, "heso-1.0-vectors.json")
CROWN_PATH = os.path.join(_VEC_DIR, "heso-1.0-crown-vectors.json")
WIRE_PATH = os.path.join(_VEC_DIR, "heso-1.0-wire-vectors.json")
TAXONOMY_PATH = os.path.join(os.path.dirname(_VEC_DIR), "taxonomy.toml")


def _is_placeholder(value) -> bool:
    return isinstance(value, str) and value.startswith(PLACEHOLDER_PREFIX)


def _contains_placeholder(obj) -> bool:
    if isinstance(obj, str):
        return _is_placeholder(obj)
    if isinstance(obj, dict):
        return any(_contains_placeholder(v) for v in obj.values())
    if isinstance(obj, list):
        return any(_contains_placeholder(v) for v in obj)
    return False


class Report:
    def __init__(self) -> None:
        self.passed = 0
        self.failures: list[str] = []
        self.pending: list[str] = []

    def ok(self) -> None:
        self.passed += 1

    def fail(self, label: str, expected, actual) -> None:
        self.failures.append(f"{label}\n    expected: {expected}\n    actual:   {actual}")

    def pend(self, label: str) -> None:
        self.pending.append(label)


# ── Legacy web-observation corpus ───────────────────────────────────────────
def run_legacy(rep: Report) -> None:
    with open(LEGACY_PATH, encoding="utf-8") as fh:
        vectors = json.load(fh)

    for vec in vectors.get("plat_vectors", []):
        vid = vec.get("id", "?")
        expected = vec.get("plat_hash")
        actual = hv.plat_hash(vec["input_json"])
        if _is_placeholder(expected):
            rep.pend(f"plat/{vid}: plat_hash awaiting reference (got {actual})")
            continue
        if actual != expected:
            rep.fail(f"plat/{vid}: plat_hash mismatch", expected, actual)
        else:
            rep.ok()

    if "sealed_envelope_vector" in vectors:
        vec = vectors["sealed_envelope_vector"]
        envelope = vec.get("sealed_envelope_json")
        if _contains_placeholder(envelope):
            rep.pend("sealed_envelope_vector: awaiting reference constants")
        else:
            actual = hv.verify_sealed_plat(envelope)
            expected = vec.get("expected_outcome")
            if actual != expected:
                rep.fail("sealed_envelope_vector: outcome mismatch", expected, actual)
            else:
                rep.ok()


# ── Crown-jewel corpus ──────────────────────────────────────────────────────
def run_action_receipts(crown: dict, rep: Report) -> None:
    block = crown.get("action_receipt_v2")
    if not block:
        return
    for case in block.get("cases", []):
        cid = case["id"]
        expected = case["expected_outcome"]
        actual = hv.verify_action_receipt(case["receipt_json"])
        if actual != expected:
            rep.fail(f"action_receipt_v2/{cid}: outcome mismatch", expected, actual)
            continue
        rep.ok()


def run_chain(crown: dict, rep: Report) -> None:
    block = crown.get("chain")
    if not block:
        return
    for case in block.get("cases", []):
        cid = case["id"]
        expected = case["expected_outcome"]
        actual = hv.verify_chain(case["chain_jsonl"])
        if actual != expected:
            rep.fail(f"chain/{cid}: outcome mismatch", expected, actual)
            continue
        rep.ok()


def run_redaction(crown: dict, rep: Report) -> None:
    block = crown.get("redaction")
    if not block:
        return
    # The full ActionReceipt carrying the commit-and-reveal record must verify
    # (the commitment rides inside the signed action_hash).
    receipt = block.get("receipt_json")
    if receipt is not None:
        expected = block.get("receipt_expected_outcome", "Valid")
        actual = hv.verify_action_receipt(receipt)
        if actual != expected:
            rep.fail("redaction/receipt: outcome mismatch", expected, actual)
        else:
            rep.ok()
    for case in block.get("cases", []):
        cid = case["id"]
        expected = case["reveal_verifies"]
        # The marker carries the algorithm + the commitment the reveal must match.
        commitment = case.get("commitment") or case.get("commitment_to_match")
        marker = {
            "field_path": case["field_path"],
            "algorithm": block["algorithm"],
            "commitment": commitment,
        }
        value_json = json.dumps(case["value_json"]).encode()
        actual = hv.verify_reveal(case["field_path"], case["salt_hex"], value_json, marker)
        if actual != expected:
            rep.fail(f"redaction/{cid}: reveal_verifies mismatch", expected, actual)
            continue
        rep.ok()


def run_taxonomy_classify(crown: dict, rep: Report) -> None:
    block = crown.get("taxonomy_classify")
    if not block:
        return
    classes = hv.load_taxonomy(TAXONOMY_PATH)
    for case in block.get("cases", []):
        cid = case["id"]
        got = hv.classify(case["facts"], classes)
        want = {
            "class": case["expected_class"],
            "verb": case["expected_verb"],
            "primitive": case["expected_primitive"],
            "effect": case["expected_effect"],
        }
        actual = {k: got[k] for k in ("class", "verb", "primitive", "effect")}
        if actual != want:
            rep.fail(f"taxonomy_classify/{cid}: classification mismatch", want, actual)
            continue
        if case.get("deny_unknown") and not got["deny_unknown"]:
            rep.fail(f"taxonomy_classify/{cid}: residual not deny-unknown", True, False)
            continue
        rep.ok()

    # RECOMPUTE taxonomy_hash from taxonomy.toml and assert it equals the pinned
    # kernel golden — a real cross-language check, NOT the old wire pass-through.
    pinned = block.get("taxonomy_hash")
    if pinned is not None:
        actual_hash = hv.taxonomy_hash(TAXONOMY_PATH)
        if actual_hash != pinned:
            rep.fail("taxonomy_classify/taxonomy_hash: recompute mismatch", pinned, actual_hash)
        else:
            rep.ok()


def run_rfc6962(crown: dict, rep: Report) -> None:
    block = crown.get("rfc6962")
    if not block:
        return
    # empty root
    actual = hv.rfc6962_empty_root().hex()
    if actual != block["empty_root_hex"]:
        rep.fail("rfc6962/empty_root", block["empty_root_hex"], actual)
    else:
        rep.ok()
    # single leaf hash
    sl = block["single_leaf"]
    actual = hv.rfc6962_leaf_hash(bytes.fromhex(sl["value_hex"])).hex()
    if actual != sl["leaf_hash_hex"]:
        rep.fail("rfc6962/single_leaf", sl["leaf_hash_hex"], actual)
    else:
        rep.ok()
    # node hash
    ne = block["node_example"]
    actual = hv.rfc6962_node_hash(
        bytes.fromhex(ne["left_hex"]), bytes.fromhex(ne["right_hex"])
    ).hex()
    if actual != ne["node_hash_hex"]:
        rep.fail("rfc6962/node", ne["node_hash_hex"], actual)
    else:
        rep.ok()
    # inclusion proof
    inc = block["inclusion"]
    ok = hv.rfc6962_verify_inclusion(
        bytes.fromhex(inc["leaf_value_hex"]),
        inc["leaf_index"],
        inc["tree_size"],
        [bytes.fromhex(h) for h in inc["proof_hex"]],
        bytes.fromhex(inc["expected_root_hex"]),
    )
    if not ok:
        rep.fail("rfc6962/inclusion", True, False)
    else:
        rep.ok()
    # consistency proofs (RFC-6962 §2.1.2) — recompute, never pass-through.
    cons = block.get("consistency")
    if cons:
        for case in cons.get("cases", []):
            cid = f"cons({case['old_size']},{case['new_size']})"
            ok = hv.rfc6962_verify_consistency(
                case["old_size"],
                bytes.fromhex(case["old_root_hex"]),
                case["new_size"],
                bytes.fromhex(case["new_root_hex"]),
                [bytes.fromhex(h) for h in case["proof_hex"]],
            )
            if not ok:
                rep.fail(f"rfc6962/consistency/{cid}", True, False)
            else:
                rep.ok()


def run_quorum(crown: dict, rep: Report) -> None:
    """Recompute each quorum leg's approver cosign payload clean-room and compare to
    the kernel-emitted ``cosign_payload_hex`` — a real per-leg cross-check (the
    clean-room receipt verifier still REFUSES a quorum body, so this is the only
    place the multi-approver byte rule is checked end-to-end)."""
    block = crown.get("quorum")
    if not block:
        return
    try:
        base = hv.quorum_operator_base(
            block["suspended_content"], block["threshold"], block["roster"]
        )
    except ValueError as e:
        rep.fail("quorum/base", "built", str(e))
        return
    if base["action_hash"] != block["base_action_hash"]:
        rep.fail("quorum/base_action_hash", block["base_action_hash"], base["action_hash"])
    else:
        rep.ok()
    for leg in block.get("legs", []):
        ident = leg["approver_identity"]
        record = {
            "decision": leg["decision"],
            "approver_identity": ident,
            "reason": leg["reason"],
            "decided_at": leg["decided_at"],
        }
        if "sla_minutes" in leg:
            record["sla_minutes"] = leg["sla_minutes"]
        actual = hv.multi_approval_cosign_payload(base, record).hex()
        if actual != leg["cosign_payload_hex"]:
            rep.fail(f"quorum/leg/{ident}: cosign payload", leg["cosign_payload_hex"], actual)
        else:
            rep.ok()


def run_time_anchor(crown: dict, rep: Report) -> None:
    """Recompute the pre-anchor ``anchored_content_hash`` clean-room and compare to
    the kernel-emitted golden; assert the documented absent-anchor outcome tags."""
    block = crown.get("time_anchor")
    if not block:
        return
    actual = hv.anchored_content_hash(block["content"])
    if actual != block["anchored_content_hash"]:
        rep.fail("time_anchor/anchored_content_hash", block["anchored_content_hash"], actual)
    else:
        rep.ok()
    # The two absent-anchor outcome tags are spec semantics (not emitted hashes);
    # pin them so a future verifier that softened fail-closed is caught.
    outcomes = block.get("outcomes", {})
    want_outcomes = {
        "anchor_required_no_anchor": "AnchorRequired",
        "no_requirement_no_anchor": "NoTrustedTime",
    }
    if outcomes != want_outcomes:
        rep.fail("time_anchor/outcomes", want_outcomes, outcomes)
    else:
        rep.ok()


def run_dsse(crown: dict, rep: Report) -> None:
    block = crown.get("dsse_pae")
    if not block:
        return
    body = bytes.fromhex(block["body_bytes_hex"])
    actual_pae = hv.dsse_pae(block["payload_type"], body).hex()
    if actual_pae != block["pae_hex"]:
        rep.fail("dsse_pae/pae_bytes", block["pae_hex"], actual_pae)
    else:
        rep.ok()
    ok = hv.verify_dsse(block["envelope_json"], block["operator_public_key_b64"])
    if not ok:
        rep.fail("dsse_pae/envelope_verify", True, False)
    else:
        rep.ok()


# ── Commitment WIRE-PAYLOAD corpus (P3, ADR-0003) ───────────────────────────
def _project_commitment(case: dict, common: dict) -> dict:
    """Clean-room re-derivation of the FULL receipt -> commitment+indexes
    projection (ADR-0003 §4). INDEPENDENT of the generator: re-reads the source
    receipt + recomputes the kernel chain head, copies ONLY the §3.1 columns. The
    classification triple (primitive/coarse_verb/resource_class/decision) is the
    recorded index the wire vector pins; everything else is recomputed from the
    receipt so byte-equality is a real cross-check, not a copy."""
    wire = case["wire_payload"]
    content = case["source_receipt_json"]["content"]
    derived = {
        "wire_version": common["wire_version"],
        "action_hash": content["action_hash"],
        "chain_prev": content.get("prev_receipt_hash"),
        "chain_head": hv.link_hash(content),
        "session_id": content.get("session_id"),
        "seq": content.get("seq"),
        "primitive": wire["primitive"],
        "coarse_verb": wire["coarse_verb"],
        "taxonomy_hash": common["taxonomy_hash"],
        "resource_class": wire["resource_class"],
        "trust_level": content["trust_level"],
        "decision": wire["decision"],
        "occurred_at": content["captured_at"],
        "signer_fpr": wire["signer_fpr"],
        "signature": case["source_receipt_json"]["signatures"][0]["signature"],
        "envelope_kind": common["envelope_kind"],
    }
    # carry the optional redaction merkle root through unchanged (a hash, not a value)
    if "redaction_merkle_root" in wire:
        derived["redaction_merkle_root"] = wire["redaction_merkle_root"]
    return derived


def run_wire(rep: Report) -> None:
    if not os.path.exists(WIRE_PATH):
        rep.pend("wire vectors file missing — run vectors/generate_wire_vectors.py")
        return
    with open(WIRE_PATH, encoding="utf-8") as fh:
        wire = json.load(fh)

    cw = wire.get("commitment_wire")
    if cw:
        common = {
            "wire_version": cw["wire_version"],
            "taxonomy_hash": cw["taxonomy_hash"],
            "envelope_kind": cw["envelope_kind"],
        }
        forbidden = cw["forbidden_on_wire"]
        for case in cw["cases"]:
            cid = case["id"]
            # 1. the source receipt must itself verify (rust-reference fingerprint)
            actual = hv.verify_action_receipt(case["source_receipt_json"])
            expected = case.get("source_receipt_expected_outcome", "Valid")
            if actual != expected:
                rep.fail(f"wire/commitment_wire/{cid}: source receipt", expected, actual)
                continue
            # 2. the clean-room projection must byte-match the recorded wire payload
            derived = _project_commitment(case, common)
            if derived != case["wire_payload"]:
                rep.fail(
                    f"wire/commitment_wire/{cid}: projection mismatch",
                    derived,
                    case["wire_payload"],
                )
                continue
            # 3. no raw content survives onto the wire
            blob = json.dumps(case["wire_payload"], ensure_ascii=False)
            leaked = [n for n in forbidden if n in blob]
            if leaked:
                rep.fail(f"wire/commitment_wire/{cid}: raw content on wire", [], leaked)
                continue
            rep.ok()

    rb = wire.get("redact_before_sign")
    if rb:
        # the redacted source receipt verifies (commitment rides in the signed hash)
        actual = hv.verify_action_receipt(rb["source_receipt_json"])
        expected = rb.get("source_receipt_expected_outcome", "Valid")
        if actual != expected:
            rep.fail("wire/redact_before_sign/receipt", expected, actual)
        else:
            rep.ok()
        # neither raw value nor reveal salt is anywhere on the wire payload
        wire_blob = json.dumps(rb["wire_payload"], ensure_ascii=False)
        commit_case = next(
            (c for c in rb["cases"] if c.get("salt_hex") and c.get("reveal_verifies")), None
        )
        if commit_case:
            if commit_case["value_json"] in wire_blob:
                rep.fail("wire/redact_before_sign: raw value on wire", False, True)
            elif commit_case["salt_hex"] in wire_blob:
                rep.fail("wire/redact_before_sign: reveal salt on wire", False, True)
            else:
                rep.ok()
        # reveal recomputation (correct salt verifies, bad salt does not)
        for case in rb["cases"]:
            cid = case["id"]
            expected = case["reveal_verifies"]
            commitment = case.get("commitment") or case.get("commitment_to_match")
            marker = {
                "field_path": case["field_path"],
                "algorithm": rb["algorithm"],
                "commitment": commitment,
            }
            value_json = json.dumps(case["value_json"]).encode()
            got = hv.verify_reveal(case["field_path"], case["salt_hex"], value_json, marker)
            if got != expected:
                rep.fail(f"wire/redact_before_sign/{cid}: reveal_verifies", expected, got)
                continue
            rep.ok()

    # ── commitment_envelope (KERNEL-EMITTED, CORE-WIRE §0 / VERIFY-GAP #2) ────
    ce = wire.get("commitment_envelope")
    if ce:
        # The fingerprint rule: signer_fpr == blake3(pubkey), NOT signer_fingerprint.
        pinned_fpr = ce.get("signer_fpr")
        derived_fpr = hv.commitment_fpr(ce["operator_public_key_b64"])
        if derived_fpr != pinned_fpr:
            rep.fail("wire/commitment_envelope/signer_fpr", pinned_fpr, derived_fpr)
        else:
            rep.ok()
        for case in ce["cases"]:
            cid = case["id"]
            env = case["envelope_json"]
            # 1. clean-room JCS bytes byte-match the kernel-emitted canonical hex
            actual_canon = hv.commitment_envelope_canonical_bytes(env).hex()
            if actual_canon != case["envelope_canonical_bytes_hex"]:
                rep.fail(
                    f"wire/commitment_envelope/{cid}: canonical bytes",
                    case["envelope_canonical_bytes_hex"],
                    actual_canon,
                )
                continue
            # 2. the detached signature verifies under COMMITMENT_SIGNING_DOMAIN, the
            #    fingerprint binds — the full reject-more verdict matches expectation
            verdict = hv.verify_commitment(
                env, case["signer_pubkey_b64"], case["signature_b64"], case["signer_fpr"]
            )
            if verdict != case["expected_verdict"]:
                rep.fail(
                    f"wire/commitment_envelope/{cid}: verify_commitment",
                    case["expected_verdict"],
                    verdict,
                )
                continue
            # 3. optionality contract: ERT-absent OMITS the ERT keys (no null/sentinel)
            if not case["ert_present"]:
                if "taxonomy_hash" in env or "resource_class" in env:
                    rep.fail(
                        f"wire/commitment_envelope/{cid}: ERT keys must be OMITTED",
                        "omitted",
                        sorted(env.keys()),
                    )
                    continue
            else:
                if "taxonomy_hash" not in env or "resource_class" not in env:
                    rep.fail(
                        f"wire/commitment_envelope/{cid}: ERT keys must be present",
                        "present",
                        sorted(env.keys()),
                    )
                    continue
            if not case["chain_present"]:
                if any(k in env for k in ("chain_prev", "session_id", "seq")):
                    rep.fail(
                        f"wire/commitment_envelope/{cid}: chain keys must be OMITTED",
                        "omitted",
                        sorted(env.keys()),
                    )
                    continue
            else:
                if not all(k in env for k in ("chain_prev", "session_id", "seq")):
                    rep.fail(
                        f"wire/commitment_envelope/{cid}: chain keys must be present",
                        "present",
                        sorted(env.keys()),
                    )
                    continue
            # never a null sentinel anywhere in the signed bytes
            if "null" in hv.commitment_envelope_canonical_bytes(env).decode():
                rep.fail(f"wire/commitment_envelope/{cid}: null in canonical bytes", False, True)
                continue
            rep.ok()
        # 4. a tampered queryable field must NOT still verify Valid (reject-more)
        absent = next((c for c in ce["cases"] if c["id"] == "CE-ERT-ABSENT"), None)
        if absent:
            tampered = dict(absent["envelope_json"])
            tampered["decision"] = "block"
            v = hv.verify_commitment(
                tampered, absent["signer_pubkey_b64"], absent["signature_b64"], absent["signer_fpr"]
            )
            if v == "Valid":
                rep.fail("wire/commitment_envelope/tamper: must reject", "InvalidSignature", v)
            else:
                rep.ok()

    # ── chained_receipt (KERNEL-EMITTED, CORE-WIRE A.4 / VERIFY-GAP #3) ───────
    cr = wire.get("chained_receipt")
    if cr:
        for case in cr["cases"]:
            cid = case["id"]
            receipt = case["receipt_json"]
            # the chained receipt itself verifies (carries seq/session_id/prev)
            actual = hv.verify_action_receipt(receipt)
            if actual != case["expected_outcome"]:
                rep.fail(f"wire/chained_receipt/{cid}: receipt", case["expected_outcome"], actual)
                continue
            # the action_hash is the kernel BLAKE3 over the (chain-field-carrying) body
            recomputed = hv.action_content_hash(receipt["content"])
            if recomputed != case["action_hash"]:
                rep.fail(
                    f"wire/chained_receipt/{cid}: action_hash", case["action_hash"], recomputed
                )
                continue
            rep.ok()
        # the successor's prev_receipt_hash MUST equal the genesis link_hash (threading)
        genesis = next((c for c in cr["cases"] if c["id"] == "CHAIN-GENESIS"), None)
        succ = next((c for c in cr["cases"] if c["id"] == "CHAIN-SUCCESSOR"), None)
        if genesis and succ:
            genesis_link = hv.link_hash(genesis["receipt_json"]["content"])
            if succ["prev_receipt_hash"] != genesis_link:
                rep.fail(
                    "wire/chained_receipt/thread: prev != genesis link",
                    genesis_link,
                    succ["prev_receipt_hash"],
                )
            else:
                rep.ok()
        # the full chain verifies in-order
        chain_jsonl = cr.get("chain_jsonl")
        if chain_jsonl:
            actual = hv.verify_chain(chain_jsonl)
            if actual != cr["chain_expected_outcome"]:
                rep.fail("wire/chained_receipt/chain", cr["chain_expected_outcome"], actual)
            else:
                rep.ok()

        # ── REGRESSION GATE: the standalone goldens are UNMOVED (VERIFY-GAP #3) ──
        # Emitting chained/commitment artifacts must NOT perturb the chain-field-ABSENT
        # standalone receipt goldens. Re-derive the L0 standalone action_hash from the
        # chain-absent body and assert it still equals 988baa2e…; assert the chained
        # successor (chain fields PRESENT) hashes to a DIFFERENT value (proving the
        # fields entered the signed string). The f599f21b… L1 golden is pinned in the
        # kernel's commitment_seam regression test.
        standalone = cr.get("standalone_goldens_unmoved", {})
        l0_golden = standalone.get("l0_action_hash")
        if l0_golden:
            # The chain-field-ABSENT L0 body = the genesis content with session_id/seq/
            # prev stripped — the original standalone fixed_content. Recompute its hash.
            genesis_content = dict(genesis["receipt_json"]["content"]) if genesis else {}
            standalone_body = {
                k: v
                for k, v in genesis_content.items()
                if k not in ("session_id", "seq", "prev_receipt_hash")
            }
            recomputed_l0 = hv.action_content_hash(standalone_body) if standalone_body else None
            if recomputed_l0 != l0_golden:
                rep.fail(
                    "wire/chained_receipt/UNMOVED: standalone L0 golden moved",
                    l0_golden,
                    recomputed_l0,
                )
            else:
                rep.ok()
            # And the chained successor (fields present) is a DIFFERENT hash — the
            # success-path byte change is real, not a no-op.
            if succ and succ["action_hash"] == l0_golden:
                rep.fail(
                    "wire/chained_receipt/UNMOVED: chained hash collided with standalone",
                    "distinct",
                    succ["action_hash"],
                )
            else:
                rep.ok()

    pi = wire.get("primitive_index")
    if pi:
        # the five-spine enum and the per-case primitive must agree with ADR-0001
        spine = set(pi["primitive_enum"])
        if spine != {"move-value", "destroy", "change-authority", "disclose", "execute"}:
            rep.fail("wire/primitive_index: spine drift", "5-spine", sorted(spine))
        else:
            rep.ok()
        for case in pi["cases"]:
            cid = case["id"]
            if case["primitive"] not in spine:
                rep.fail(f"wire/primitive_index/{cid}: unknown primitive", spine, case["primitive"])
                continue
            if case["decision"] not in pi["decision_enum"]:
                rep.fail(
                    f"wire/primitive_index/{cid}: unknown decision",
                    pi["decision_enum"],
                    case["decision"],
                )
                continue
            rep.ok()


def run_crown(rep: Report) -> None:
    if not os.path.exists(CROWN_PATH):
        rep.pend("crown vectors file missing — run vectors/generate_vectors.py")
        return
    with open(CROWN_PATH, encoding="utf-8") as fh:
        crown = json.load(fh)
    run_action_receipts(crown, rep)
    run_chain(crown, rep)
    run_redaction(crown, rep)
    run_taxonomy_classify(crown, rep)
    run_rfc6962(crown, rep)
    run_quorum(crown, rep)
    run_time_anchor(crown, rep)
    run_dsse(crown, rep)


def main() -> int:
    rep = Report()
    run_legacy(rep)
    run_crown(rep)
    run_wire(rep)

    for line in rep.pending:
        print(f"PENDING  {line}")
    for line in rep.failures:
        print(f"FAIL     {line}")

    print(f"\n{rep.passed} passed, {len(rep.failures)} failed, {len(rep.pending)} pending")
    return 1 if (rep.failures or rep.pending) else 0


if __name__ == "__main__":
    sys.exit(main())
